In [14]:
import numpy as np

#切片 slicing

# 1. ndarray[start:end]
# 2. ndarray[start:]
# 3. ndarray[:end]

x = np.arange(1,21).reshape(4,5)
print(x)

x1=x[1:4, 2:4] #1:2 目标开始行和结束行，2:5 目标开始列和结束列
print('x1:\n',x1)

x2=x[:, 2:4] 
print('x2:\n',x2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
x1:
 [[ 8  9]
 [13 14]
 [18 19]]
x2:
 [[ 3  4]
 [ 8  9]
 [13 14]
 [18 19]]


In [22]:
# copy
x = np.arange(1,21).reshape(4,5)
# x1=x[1:4, 2:4]
# print(x1)
# x1[1][1] = 22222
# print(x)

x2=x[1:4, 2:4].copy()

x2[1][1] = 22222
print(x,x2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]] [[    8     9]
 [   13 22222]
 [   18    19]]


In [26]:
x = np.arange(20).reshape(4,5)
print(x)
indices=np.array([1,3]) #指数
y=x[indices,:] #第二和第四行
print(y)
z=x[:,indices]
print(z)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[ 5  6  7  8  9]
 [15 16 17 18 19]]
[[ 1  3]
 [ 6  8]
 [11 13]
 [16 18]]


In [32]:
# 对角线上 diag
print(x)
z = np.diag(x)
print('z:\n',z)

z = np.diag(x, k=1)
print('z:\n',z)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
z:
 [ 0  6 12 18]
z:
 [ 1  7 13 19]


In [34]:
# unique 提取独一无二的值
x=np.array( [[1,2,1],[3,3,5],[1,3,5]])
print(np.unique(x))

[1 2 3 5]


In [ ]:
# 进阶
# 布尔索引
# 集合运行
# 排序

In [47]:
x = np.arange(25).reshape(5,5)
print(x)

print('选出大于10的值:\n', x[x>10])
print('选出奇数:\n', x[x%2!=0])
print(x[(x>7) & (x<10)])

#赋值
x[(x>7) & (x<10)] = -1
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
选出大于10的值:
 [11 12 13 14 15 16 17 18 19 20 21 22 23 24]
选出奇数:
 [ 1  3  5  7  9 11 13 15 17 19 21 23]
[8 9]
[[ 0  1  2  3  4]
 [ 5  6  7 -1 -1]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [62]:
# 集合运算
x = np.array([1,2,3,4,5])
y = np.array([6,7,2,8,4])

print( np.intersect1d(x,y) )
print(np.setdiff1d(x,y))
print(np.union1d(x,y))


[2 4]
[1 3 5]
[1 2 3 4 5 6 7 8]


In [ ]:
# 排序

