In [3]:
import numpy as np

x = np.array([1,2,3,4,5])
print(x)

[1 2 3 4 5]


In [4]:
# 负数索引
print(x[-1])

5


In [10]:
#修改值
x[2]=20
print(x)

#修改秩为2的数组
y = np.arange(1,10).reshape(3,3)
print(y)
y[2,2]=200
print(y)

[ 1  2 20  4  5]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[  1   2   3]
 [  4   5   6]
 [  7   8 200]]


In [18]:
#删除
x = np.array([1,2,3,4,5])
x = np.delete(x,[0,4])
print(x)
# w = np.delete(y, 0, axis=0)
# print(w)

[2 3 4]


In [20]:
y = np.arange(1,10).reshape(3,3)
print(y)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [21]:
y = np.delete(y, 0, axis=1)
print(y)

[[2 3]
 [5 6]
 [8 9]]


In [38]:
y = np.arange(1,10).reshape(3,3)
y = np.delete(y, 1, axis=1)
print(y)

[[1 3]
 [4 6]
 [7 9]]


In [43]:
#追加行 追加列
v=np.arange(1,10).reshape(3,3)
v1=np.append(v,[[10],[11],[12]], axis=1)
v2=np.append(v,[10,11,12])
print(v1,v2)

[[ 1  2  3 10]
 [ 4  5  6 11]
 [ 7  8  9 12]] [ 1  2  3  4  5  6  7  8  9 10 11 12]


In [68]:
# insert
x = np.array([1,2,3,4,5])
print('x:\n',x)
x = np.insert(x, 2,[100,1000])
print(x)

y=np.arange(1,10).reshape(3,3)
print('y:\n',y)
y=np.insert(y, 1,[10,10,10], axis=1)
print(y)

v=np.insert(y,0,500,axis=1)
print(v)

x:
 [1 2 3 4 5]
[   1    2  100 1000    3    4    5]
y:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1 10  2  3]
 [ 4 10  5  6]
 [ 7 10  8  9]]
[[500   1  10   2   3]
 [500   4  10   5   6]
 [500   7  10   8   9]]


In [103]:
# vstack， hstack 堆叠 
x = np.array([0,0])
y=np.array([[2,3],[5,6]])
z=np.vstack((x,y))
print(z)


w=np.hstack( (y, x.reshape(2,1)))
print(w)

[[0 0]
 [2 3]
 [5 6]]
[[2 3 0]
 [5 6 0]]


In [ ]:
# 切片
